### ISSUE TITLE
Please rename to 2015-07-13-perth

### ISSUE THREAD

**Issue by gvwilson** [arohl/2015-07-20-perth#1]
Hi,
Can you please rename this repo `2015-07-13-perth`, or create a new one with that name?  Our convention is to use YYYY-MM-DD-site for workshop repositories so that we can keep track of them all.
Thanks, 
Greg

**Comment by arohl** [comment]
Greg - although we have a month we are pretty sure about, we aren't at all sure of the day. We were asked to set up the page as part of the train the trainer workshop. Can I just call it 2015-07-XX-perth for the moment?

  Andrew

**Comment by gvwilson** [comment]
Hi Andrew,
Happy to wait until you have the day and then list it (our validation 
tools will complain about an 'XX' in the date).
Cheers,
Greg

On 2015-03-02 8:02 AM, arohl wrote:

> Greg - although we have a month we are pretty sure about, we aren't at 
> all sure of the day. We were asked to set up the page as part of the 
> train the trainer workshop. Can I just call it 2015-07-XX-perth for 
> the moment?
> 
> Andrew
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/arohl/perth-2015/issues/1#issuecomment-76707905.

## 

Email longa, vita brevis.

**Comment by arohl** [comment]
OK - should now have right naming... Note we have changed the date so its good we waited ;-)
